#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#and similarly for PyPy too.
language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"

before_install:
  - "export PY2=no"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PY2=yes; fi"

install:
  - "/usr/bin/yes | python setup.py install"

before_script:
  - "pip freeze"

script:
  - "nosetests -vv --with-coverage"
